---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: 'k6-test'
      files:
        - file: 'test-script.js'
        - file: 'base-test.js'
        - file: 'soak-test.js'
        - file: 'spike-test.js' 